---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-pods-monitor
  namespace: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      monitoring: "enabled"
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  - port: http
    path: /actuator/prometheus
    interval: 30s
  namespaceSelector:
    any: true
