---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka-alerts
  namespace: monitoring
  labels:
    app: monitoring
spec:
  groups:
  - name: kafka.rules
    rules:
    - alert: KafkaBrokerDown
      expr: kafka_brokers < 3
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Kafka broker is down"
        description: "Kafka cluster has only {{ $value }} brokers running, expected 3"
    
    - alert: KafkaConsumerLag
      expr: kafka_consumer_lag_sum > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High consumer lag detected"
        description: "Consumer group {{ $labels.consumergroup }} has lag of {{ $value }} messages"
    
    - alert: KafkaUnderReplicatedPartitions
      expr: kafka_cluster_partition_under_replicated > 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Kafka under-replicated partitions"
        description: "{{ $value }} partitions are under-replicated"
