---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-cluster
  namespace: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      strimzi.io/name: kafka-kafka-bootstrap
  endpoints:
  - port: tcp-prometheus
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - kafka
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      strimzi.io/name: kafka-kafka-exporter
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - kafka