---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-monitor
  namespace: prometheus-operator
  labels:
    app: kafka
    type: metrics
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  namespaceSelector:
    matchNames:
      - kafka
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
