---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-history-server
  namespace: monitoring
  labels:
    app: monitoring
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: spark-history-server
  endpoints:
  - port: web
    path: /metrics/prometheus
    interval: 30s
  namespaceSelector:
    matchNames:
    - spark-system
    - default
