---
# ServiceMonitor for Spark History Server
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-history-server
  namespace: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      app: spark-history-server
  endpoints:
  - port: web
    path: /metrics/prometheus
    interval: 30s
  namespaceSelector:
    matchNames:
    - spark-system
    - default
