---
kind: Secret
apiVersion: v1
metadata:
  name: repo-user-secret
  namespace: apps
type: Opaque
stringData:
  # MONGODB
  REPO_USER_MONGODB_ENDPOINT: "mongodb://admin:admin@mongos.mongo.svc.cluster.local:27017/RepoUser?authSource=RepoUser&w=majority"
