{
 "title": "Real Time",
 "time": { "from": "2025-07-02T23:43:56.152Z", "to": "2025-07-04T06:09:12.952Z" },
 "templating": {
  "list": [
   { "name": "day" },
   {
    "name": "hour",
    "query": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23"
   }
  ]
 },
 "panels": [
  {
   "title": "Revenue per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "command": "ts.range",
     "filter": "parking-stats:timeseries:2025-07-03:entries",
     "keyName": "parking-stats:timeseries:$day:revenue_simulation",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Money Made In The Last Hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "JSON.GET parking-stats:hourly:$day:$hour .RevenueSimulation",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Number of Entries in the last hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Entries" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyName": "parking-stats:hourly:2025-07-03:12",
     "path": "GET parking-stats:hourly:2025-07-03:12 .NbrExit",
     "query": "JSON.GET parking-stats:hourly:$day:$hour .NbrEntries",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Number of Exits in the last hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Exits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyName": "parking-stats:hourly:2025-07-03:12",
     "path": "GET parking-stats:hourly:2025-07-03:12 .NbrExit",
     "query": "JSON.GET parking-stats:hourly:$day:$hour .NbrExit",
     "type": "cli"
    }
   ]
  }
 ]
}