apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvc-notifier
  namespace: apps
  labels:
    app: srvc-notifier
    type: backends
spec:
  # replicas: 1 # managed by hpa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: srvc-notifier
  template:
    metadata:
      labels:
        app: srvc-notifier
        monitoring: "enabled"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090" 
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: srvc-notifier
          image: registry.cri.epita.fr/mateo.lelong/inde1/srvc-notifier:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          envFrom:
            - configMapRef:
                name: apps-config
            - secretRef:
                name: redis-secrets
            - secretRef:
                name: srvc-notifier-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          # livenessProbe:
          #   httpGet:
          #     path: /liveness
          #     port: 8080
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8080
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
