---
apiVersion: v1
kind: Secret
metadata:
  name: srvc-notifier-secrets
  namespace: apps
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1391037564021899315/ml3IegeME8OP0naWRFsskTWb_9pO11h5UzsfDaQjHZw3Iwi2bH0U5dyBeiZNCvYMlGVa
