include:
  - "ci/common.gitlab-ci.yml"
  - "ci/repo-account.gitlab-ci.yml"
  - "ci/srvc-alert.gitlab-ci.yml"
  - "ci/srvc-stats.gitlab-ci.yml"
  - "ci/srvc-notifier.gitlab-ci.yml"
  - "ci/srvc-io.gitlab-ci.yml"

verify-commit-message:
  image: alpine:3.18
  stage: verify-commit-message
  script:
    - |
      if ! echo $CI_COMMIT_MESSAGE | grep -qE '(repo-account|srvc-io|srvc-stats|srvc-alert|srvc-notifier|k8s)'; then
        echo "Commit message must contains AT LEAST the name of one of the services to trigger the associated CI."
        exit 1
      fi

stages:
  - verify-commit-message
  - lint
  - test
  - build
