---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srvc-stats-ingress
  namespace: spark
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /spark/srvc-stats
            pathType: Prefix
            backend:
              service:
                name: srvc-stats
                port:
                  number: 4040
