---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: srvc-stats
  namespace: spark
spec:
  type: Scala
  mode: cluster
  sparkVersion: "3.5.5"
  image: "spark:3.5.5"
  imagePullPolicy: IfNotPresent
  mainClass: srvc_stats.Main
  mainApplicationFile: "local:///opt/spark/app/target/scala-2.13/srvc-stats-assembly-0.1.0.jar"
  arguments:
    - "10000"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 2
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 20
  timeToLiveSeconds: 1800
  sparkConf:
    "spark.executor.instances": "1"
    "spark.kubernetes.executor.deleteOnTermination": "true"
    "spark.kubernetes.driver.deleteOnTermination": "true"
    "spark.executor.heartbeatInterval": "10s"
    "spark.network.timeout": "120s"
  driver:
    initContainers:
    - args: |
        curl -H "JOB-TOKEN: $(cat )" https://gitlab.cri.epita.fr/api/v4/projects/26539/packages/generic/srvc-stats/0.1.0/srvc-stats.0.1.0.tar.gz
        tar -xzf srvc-stats.0.1.0.tar.gz -C /opt/spark/app
      command:
      - sh
      - -c
      image: curlimages/curl:latest
      name: download-jar
      resources:
        limits:
          cpu: 50m
          memory: 0.25Gi
        requests:
          cpu: 50m
          memory: 0.25Gi
      volumeMounts:
      - mountPath: /opt/spark/app
        name: app-jar
    cores: 1
    memory: "512m"
    serviceAccount: spark-operator-spark
    labels:
      app: srvc-stats
      component: driver
  executor:
    instances: 1
    cores: 1
    memory: "512m"
    labels:
      app: srvc-stats
      component: executor
