apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: srvc-stats-daily
  namespace: spark
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  template:
    type: Scala
    mode: cluster
    sparkVersion: "3.5.5"
    image: "spark:3.5.5"
    imagePullPolicy: IfNotPresent
    mainClass: srvc_stats.MainDaily
    mainApplicationFile: "local:///opt/spark/app/target/scala-2.13/srvc-stats-assembly-0.1.0.jar"
    arguments:
      - "10000"
    restartPolicy:
      type: OnFailure
      onFailureRetries: 2
      onFailureRetryInterval: 10
      onSubmissionFailureRetries: 3
      onSubmissionFailureRetryInterval: 20
    timeToLiveSeconds: 1800
    sparkConf:
      "spark.executor.instances": "1"
      "spark.kubernetes.executor.deleteOnTermination": "true"
      "spark.kubernetes.driver.deleteOnTermination": "false"
      "spark.executor.heartbeatInterval": "10s"
      "spark.network.timeout": "120s"
    driver:
      initContainers:
        - name: download-jar
          image: curlimages/curl:latest
          command:
            - sh
            - -c
          args:
            - |
              curl -H "JOB-TOKEN: $(cat /etc/gitlab-token/token)" \
                https://gitlab.cri.epita.fr/api/v4/projects/26539/packages/generic/srvc-stats/0.1.0/srvc-stats.0.1.0.tar.gz \
                -o srvc-stats.0.1.0.tar.gz
              tar -xzf srvc-stats.0.1.0.tar.gz -C /opt/spark/app
          resources:
            limits:
              cpu: 50m
              memory: 0.25Gi
            requests:
              cpu: 50m
              memory: 0.25Gi
          volumeMounts:
            - mountPath: /opt/spark/app
              name: app-jar
            - mountPath: /etc/gitlab-token
              name: gitlab-token
              readOnly: true
      cores: 1
      memory: "512m"
      serviceAccount: spark-operator-spark
      labels:
        app: srvc-stats
        component: driver
      volumes:
        - name: app-jar
          emptyDir: {}
        - name: gitlab-token
          secret:
            secretName: gitlab-token
            items:
              - key: token
                path: token
    executor:
      instances: 1
      cores: 1
      memory: "512m"
      labels:
        app: srvc-stats
        component: executor
