apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: srvc-stats-weekly
  namespace: spark
spec:
  schedule: "0 0 * * 0"  # Run weekly on sunday at midnight
  volumes:
    - name: app-jar
      emptyDir:
        sizeLimit: 250Mi
    - name: gitlab-token
      secret:
        secretName: gitlab-token
        items:
          - key: token
            path: token
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  template:
    type: Scala
    mode: cluster
    sparkVersion: "3.5.5"
    image: "spark:3.5.5"
    imagePullPolicy: IfNotPresent
    mainClass: srvc_stats.MainHourly
    mainApplicationFile: "local:///opt/spark/app/srvc-stats-assembly-0.1.1.jar"
    arguments:
      - "10000"
    restartPolicy:
      type: OnFailure
      onFailureRetries: 2
      onFailureRetryInterval: 10
      onSubmissionFailureRetries: 3
      onSubmissionFailureRetryInterval: 20
    timeToLiveSeconds: 1800
    sparkConf:
      "spark.executor.instances": "1"
      "spark.kubernetes.executor.deleteOnTermination": "true"
      "spark.kubernetes.driver.deleteOnTermination": "false"
      "spark.executor.heartbeatInterval": "10s"
      "spark.network.timeout": "120s"
    driver:
      initContainers:
        - name: download-jar
          image: curlimages/curl:latest
          command:
            - sh
            - -c
          args:
            - |
              curl -H "PRIVATE-TOKEN: $(cat /etc/gitlab-token/token)" \
                https://gitlab.cri.epita.fr/api/v4/projects/26539/packages/generic/srvc-stats/0.1.1/srvc-stats-assembly-0.1.1.jar \
                -o /opt/spark/app/srvc-stats-assembly-0.1.1.jar
          resources:
            limits:
              cpu: 50m
              memory: 0.25Gi
            requests:
              cpu: 50m
              memory: 0.25Gi
          volumeMounts:
            - mountPath: /opt/spark/app
              name: app-jar
            - mountPath: /etc/gitlab-token
              name: gitlab-token
              readOnly: true
      cores: 1
      memory: "512m"
      serviceAccount: spark-operator-spark
      labels:
        app: srvc-stats
        component: driver
      volumeMounts:
        - mountPath: /opt/spark/app
          name: app-jar
        - mountPath: /etc/gitlab-token
          name: gitlab-token
          readOnly: true
      volumes:
        - name: app-jar
          emptyDir: {}
        - name: gitlab-token
          secret:
            secretName: gitlab-token
            items:
              - key: token
                path: token
    executor:
      instances: 3
      cores: 1
      memory: "512m"
      labels:
        app: srvc-stats
        component: executor
