apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-insight-ingress
spec:
  ingressClassName: "traefik"
  rules:
  - host: ""
    http:
      paths:
      - path: /redis
        pathType: Prefix
        backend:
          service:
            name: redis-insight-redisinsight
            port:
              number: 8001
