---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: kv
  labels:
    component: kv
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 100Mi
  redis:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 100Mi
