---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    resources:
      requests:
        memory: 6Gi
        cpu: "3"
      limits:
        memory: 6Gi
        cpu: "3"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.cleaner.dedupe.buffer.size: 1073741824    # 1GiB
      log.retention.hours: -1     # Change this to enable compaction
      log.retentions.bytes: -1    # Change this to enable compaction
      message.max.bytes: 100000000  # 100Mio
      replica.fetch.max.bytes: 100000000  # 100Mio
      default.replication.factor: 3
      min.insync.replicas: 2
    storage: {} # TODO
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1500Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 500m
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
      class: csi-rbd-sc-retain
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    logging: debug
    enableSaramaLogging: true
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
