---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    app: kafka-exporter
spec:
  ports:
    - name: kafka-exporter
      port: 9404
      targetPort: 9404
  selector:
    strimzi.io/cluster: kafka
    strimzi.io/component-type: kafka-exporter
    strimzi.io/name: kafka-kafka-exporter
