---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: "0.25"
      limits:
        memory: 1Gi
        cpu: "0.5"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      
      log.cleaner.dedupe.buffer.size: 134217728
      
      log.retention.hours: 24
      log.retention.bytes: 1073741824
      log.segment.bytes: 104857600
      
      message.max.bytes: 10485760
      replica.fetch.max.bytes: 10485760

      num.network.threads: 2
      num.io.threads: 2
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600

      log.cleaner.enable: true
      log.cleaner.threads: 1

      auto.create.topics.enable: true
      delete.topic.enable: true
      
    storage:
      type: persistent-claim
      size: 5Gi

    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 300m
    storage:
      type: persistent-claim
      size: 2Gi

    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
      
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
          
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    logging: info  # Changed from debug
    enableSaramaLogging: false  # Disabled to reduce logs
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
