---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: kafka
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "azhzLXJlZ2lzdHJ5LXRva2VuOlQyS1lGLW1BTHJBanUxb3p4RGlv"
          }
      }
    }
type: kubernetes.io/dockerconfigjson
# echo -n "k8s-registry-token:T2KYF-mALrAju1ozxDio" | base64
