---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: apps
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: apps
  sources:
    - repoURL: git@gitlab.cri.epita.fr:mateo.lelong/inde1
      targetRevision: HEAD
      path: k8s/apps

    - repoURL: git@gitlab.cri.epita.fr:mateo.lelong/inde1
      targetRevision: HEAD
      path: k8s/apps/srvc-io
      helm:
        releaseName: srvc-io
        values: |
          image:
            repository: registry.cri.epita.fr/mateo.lelong/inde1/srvc-io
            tag: "v0.2.4"
          replicas: 3
          configs:
            - parking:
                slots: "1-50,51-100,101-150"
                handicap: "1-5|10-15,51-55|60-65,101-105|110-115"
                lots: "lot-01,lot-02,lot-03"
                minDuration: "30000"
                maxDuration: "1080000"
                eventsPerSecond: 5
              vehicle:
                platePattern: "AA-ddd-aa"
                plateRandomProbability: 0.8
                colors: "red,blue,green,yellow,black,white,gray,silver"
                types: "car,truck,motorcycle,van,suv"
            - parking:
                slots: "50-100,0-50,0-100"
                handicap: "50-51,51-55|60-65,0-10"
                lots: "lot-01,lot-02,lot-03"
                minDuration: "30000"
                maxDuration: "1080000"
                eventsPerSecond: 5
              vehicle:
                platePattern: "BB-ddd-aa"
                plateRandomProbability: 0.8
                colors: "green,yellow,black,white,gray,silver"
                types: "car,van,suv"
            - parking:
                slots: "101-200,101-200,0-100"
                handicap: "101-105,101-110,0-10"
                lots: "lot-01,lot-02,lot-03"
                minDuration: "30000"
                maxDuration: "1080000"
                eventsPerSecond: 5
              vehicle:
                platePattern: "CC-ddd-aa"
                plateRandomProbability: 0.8
                colors: "green,yellow,black,white,gray,silver"
                types: "car,motorcycle,truck"
          kafka:
            topic: "parking-event-topic"  
            bootstrapServers: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
          resilience:
            maxRetries: 3
            backoffMs: 500
          monitoring:
            prometheusHost: 0.0.0.0
            prometheusPort: 9090
