---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: apps
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: apps
  source:
    repoURL: git@gitlab.cri.epita.fr:mateo.lelong/inde1
    targetRevision: HEAD
    path: k8s/apps
