---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: kafka-operator
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: kafka
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.43.0
    helm:
      values: |
        watchAnyNamespace: true
        tolerations: []
        resources:
          limits:
            memory: 384Mi
            cpu: 1000m
          requests:
            memory: 384Mi
            cpu: 200m
