---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  # ArgoCD
  - argocd.yml

  # Operators to create cluster
  - kafka-operator.yml
  - redis-operator.yml
  - spark-operator.yml

  # Applications
  - apps.yml  # Applications deployed by ArgoCD
  - redis.yml # Redis cluster
  - kafka.yml # Kafka cluster
  - spark.yml # Spark application
  - minio.yml # Datalake

  # Monitoring tools
  - redpanda.yml
  - prometheus-operator.yml # grafana + prometheus operators
  - redis-insight.yml # Redis Insight
