---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # after argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: minio
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: minio
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      releaseName: minio
      values: |
        auth:
          rootUser: admin
          rootPassword: minio123456
        persistence:
          enabled: true
          size: 20Gi
          storageClass: local-path
        replicas: 4
        drivesPerNode: 1

        minioAPIPort: 9000
        minioConsolePort: 9001
        
        service:
          type: ClusterIP
          port: 9000
        consoleService:
          type: ClusterIP
          port: 9001

        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 500m

        securityContext:
          enabled: true
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
        defaultBuckets: "datalake,json-data"

        mode: distributed

        consoleIngress:
          enabled: true
          ingressClassName: "traefik"
          path: /minio
          hosts:
            - ""
