---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: minio
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: minio
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      releaseName: minio
      values: |
        auth:
          rootUser: admin
          rootPassword: minio123456
        
        users:
          - accessKey: console
            secretKey: console123
            policy: consoleAdmin

          - accessKey: minio
            secretKey: minio123
            policy: consoleAdmin

        persistence:
          enabled: true
          size: 20Gi
          storageClass: local-path

        replicas: 4
        drivesPerNode: 1

        minioAPIPort: 9000
        minioConsolePort: 9001
        service:
          type: ClusterIP
          port: 9000
        consoleService:
          type: ClusterIP
          port: 9001

        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 500m

        securityContext:
          enabled: true
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001

        defaultBuckets: "datalake,json-data,parking-events"
        mode: distributed

        ingress:
          enabled: false

        consoleIngress:
          enabled: true
          ingressClassName: traefik
          path: /
          hosts:
            - minio.localhost
