apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: prometheus-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: prometheus-operator
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # solve deployment issues
      - Replace=true # solve deployment issues
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: prometheus-operator
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 75.3.5
      helm:
        values: |
          fullnameOverride: "prometheus"

          prometheus:
            enabled: true
            service:
              port: 9090

            ingress:
              enabled: true
              ingressClassName: "traefik"
              hosts:
                - "prometheus.localhost"
              paths:
                - /
              pathType: Prefix
              servicePort: 9090
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: web
              tls: []

          grafana:
            enabled: true
            adminPassword: admin123
            ingress:
              enabled: true
              ingressClassName: "traefik"
              path: /grafana
              pathType: Prefix
              tls: []

            sidecar:
              dashboards:
                enabled: true
                label: grafana_dashboard
                labelValue: "1"
                searchNamespace: ALL
              datasources:
                enabled: true
                defaultDatasourceEnabled: true
            grafana.ini:
              server:
                root_url: "%(protocol)s://%(domain)s/grafana/"
                serve_from_sub_path: true
              auth.anonymous:
                enabled: true
                org_role: Viewer

          alertmanager:
            enabled: true
            alertmanagerSpec:
              alertmanagerConfigSelectorNilUsesHelmValues: false
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: local-path
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi

          kubeStateMetrics:
            enabled: true

          nodeExporter:
            enabled: true

          prometheusOperator:
            enabled: true
