---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: redis-insight
  annotations:
    argocd.argoproj.io/sync-wave: "3" # after argocd, redis operator and redis
  labels:
    app: redis-insight
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: redis
  sources:
    - repoURL: https://spy86.github.io/redisinsight
      chart: redisinsight 
      targetRevision: 0.1.0
      values: |
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3

        namespace: redis

        resources:
          limits:
            memory: 512Mi
            cpu: 250m
          requests:
            memory: 256Mi
            cpu: 100m

        image:
          pullPolicy: IfNotPresent
          repository: redislabs/redisinsight
          tag: 2.70

        fullnameOverride: redis-insight

        service:
          type: ClusterIP
          port: 8080
