apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: redis-insight
  annotations:
    argocd.argoproj.io/sync-wave: "3" # after argocd, redis operator and redis
  labels:
    app: redis-insight
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: redis
  source:
    repoURL: git@gitlab.cri.epita.fr:mateo.lelong/inde1
    targetRevision: HEAD
    path: k8s/redis-insight
    helm:
      releaseName: redis-insight
      values: |
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
        namespace: redis
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
          requests:
            memory: 256Mi
            cpu: 100m
        image:
          pullPolicy: IfNotPresent
          repository: redislabs/redisinsight
          tag: "2.70"  # Quote version numbers to avoid YAML parsing issues
        fullnameOverride: redis-insight
        additionalEnv:
          - name: RI_PROXY_PATH
            value: /redis
