---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: redis-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1" # after argocd
  labels:
    app: redis-operator
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: redis
  source:
    repoURL: https://spotahome.github.io/redis-operator
    chart: redis-operator
    targetRevision: 3.2.8
    helm:
      values: |
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi

        monitoring:
          enabled: true
          serviceMonitor: true
          serviceAnnotations: {}
          prometheus:
            name: redis-operator
