apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kafka
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: "https://charts.redpanda.com"
    chart: console
    targetRevision: "0.7.29"
    helm:
      values: |
        console:
          config:
            kafka:
              brokers:
                - kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
              schemaRegistry:
                enabled: false
              protobuf:
                enabled: false
            redpanda:
              adminApi:
                enabled: false
            connect:
              enabled: false
        image:
          tag: v2.7.2
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
          hosts:
            - paths:
                - path: /redpanda
                  pathType: Prefix
        service:
          type: ClusterIP
          port: 8080
        monitoring:
          enabled: true
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
        # Pod security context
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
