apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kafka
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: "https://charts.redpanda.com"
    chart: console
    targetRevision: "v3.1.0"
    helm: # https://docs.redpanda.com/current/reference/k-console-helm-spec
      # https://github.com/redpanda-data/redpanda-operator/blob/main/charts/console/
      values: |
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3

        config: # https://docs.redpanda.com/current/console/config/configure-console/
          kafka:
            brokers: ["kafka-kafka-bootstrap.kafka.svc:9092"]
          server:
            basePath: /redpanda

        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m

        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: ""
              paths:
                - path: /redpanda
                  pathType: Prefix
          tls: []

        replicaCount: 1
