
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: minio
spec:
  entryPoints:
    - web
  routes:
    - match: Host("minio.localhost")
      kind: Rule
      services:
        - name: minio-console
          port: 9001
