apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-strip
  namespace: minio
spec:
  stripPrefix:
    prefixes:
      - /minio
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: minio
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/minio`)
      kind: Rule
      services:
        - name: minio-console # https://github.com/minio/minio/discussions/16304
          port: 9001
      middlewares:
        - name: minio-strip
