apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-strip
  namespace: minio
spec:
  stripPrefix:
    prefixes:
      - /minio
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-headers
  namespace: minio
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "http"
      X-Forwarded-For: ""
      X-Real-IP: ""
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: minio
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/minio`)
      kind: Rule
      services:
        - name: minio-console
          port: 9001
      middlewares:
        - name: minio-headers
        - name: minio-strip
