---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: https://gitlab.cri.epita.fr/mateo.lelong/inde1.git
    targetRevision: HEAD
    path: k8s/argocd
