---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "1" # after argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: minio
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: minio
  source:
    repoURL: git@gitlab.cri.epita.fr:mateo.lelong/inde1
    targetRevision: HEAD
    path: k8s/minio
