---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  labels:
    app: redis-operator
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
  destination:
    name: redis-operator
    namespace: redis
  source:
    repoURL: https://spotahome.github.io/redis-operator
    chart: redis-operator
    targetRevision: 1.2.4
