---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  labels:
    app: spark-operator
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: spark-operator
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: v2.2.0
    helm:
      values: |
        watchAnyNamespace: true
