---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-events-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
