apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: srvc-stats
  namespace: spark
spec:
  schedule: "@every 2m"
  concurrencyPolicy: Allow
  template:
    type: Scala
    mode: cluster
    sparkVersion: 3.5.5
    image: spark:3.5.5
    imagePullPolicy: IfNotPresent
    mainClass: org.apache.spark.examples.SparkPi
    mainApplicationFile: local:///opt/spark/examples/jars/spark-examples.jar

    restartPolicy:
      type: Never

    sparkUIOptions:
      ingressAnnotations:
        kubernetes.io/ingress.class: traefik

    driver:
      cores: 1
      memory: 512m
      serviceAccount: spark-operator-spark
      securityContext:
        runAsUser: 185
        runAsGroup: 185
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

    executor:
      instances: 1
      cores: 1
      memory: 512m
      securityContext:
        runAsUser: 185
        runAsGroup: 185
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
