---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: srvc-store
  namespace: spark
spec:
  type: Scala
  mode: cluster
  sparkVersion: 3.5.5
  image: spark:3.5.5
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples.jar
  arguments:
    - "5000"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  timeToLiveSeconds: 3600
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "file:///tmp/spark-events"
    "spark.history.fs.logDirectory": "file:///tmp/spark-events"
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    labels:
      version: 3.5.5
    volumeMounts:
      - name: spark-events
        mountPath: /tmp/spark-events
    securityContext:
      runAsUser: 185
      runAsGroup: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  executor:
    instances: 1
    cores: 1
    memory: 512m
    labels:
      version: 3.5.5
    volumeMounts:
      - name: spark-events
        mountPath: /tmp/spark-events
    securityContext:
      runAsUser: 185
      runAsGroup: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  volumes:
    - name: spark-events
      persistentVolumeClaim:
        claimName: spark-events-pvc
