image:
  repository: registry.cri.epita.fr/mateo.lelong/inde1/srvc-io
  tag: "v0.2.3"
replicas: 3

configs:
  - parking:
      slots: "1-50,51-100,101-150"
      handicap: "1-5|10-15,51-55|60-65,101-105|110-115"
      lots: "lot-01,lot-02,lot-03"
      minDuration: "300000"  # 5 minutes in milliseconds
      maxDuration: "10800000"  # 3 hours in milliseconds
      eventsPerSecond: 10

    vehicle:
      platePattern: "aa-ddd-aa"
      plateRandomProbability: 0.5
      colors: "red,blue,green,yellow,black,white,gray,silver"
      types: "car,truck,motorcycle,van,suv"

  - parking:
      slots: "50-100,0-50,0-100"
      handicap: "50-51,51-55|60-65,"
      lots: "lot-01,lot-02,lot-03"
      minDuration: "300000"  # 5 minutes in milliseconds
      maxDuration: "10800000"  # 3 hours in milliseconds
      eventsPerSecond: 10

    vehicle:
      platePattern: "aa-ddd-aa"
      plateRandomProbability: 0.5
      colors: "green,yellow,black,white,gray,silver"
      types: "car,van,suv"

kafka:
  topic: "parking-events"  
  bootstrapServers: "kafka:9092"

resilience:
  maxRetries: 3
  backoffMs: 500

monitoring:
  prometheusEndpoint: "http://prometheus:9090"
