---
# ConfigMap for Spark History Server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-history-config
  namespace: spark
data:
  spark-defaults.conf: |
    spark.history.fs.logDirectory=file:///tmp/spark-events
    spark.history.ui.port=18080
    spark.history.retainedApplications=50
    spark.history.ui.maxApplications=50
