---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: spark-headers
  namespace: spark
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Prefix: "/spark"
    customResponseHeaders:
      Content-Type: ""
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-history-server
  namespace: spark
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: spark-spark-headers@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /spark
            pathType: Prefix
            backend:
              service:
                name: spark-history-server
                port:
                  number: 18080
