apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-history-server
  namespace: spark
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: spark-stripprefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /spark
        pathType: Prefix
        backend:
          service:
            name: spark-history-server
            port:
              number: 18080
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: spark
spec:
  stripPrefix:
    prefixes:
    - /spark
