{{- $root := . }}
{{- range $index, $config := $root.Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: srvc-io-{{ $index }}-config
  namespace: apps
data:
  config.env: |
    LOG_LEVEL=INFO
    APP_NAME=srvc-io
    PARKING_SLOTS="{{ $config.parking.slots }}"
    HANDICAP_SLOTS="{{ $config.parking.handicap }}"
    PARKING_LOTS="{{ $config.parking.lots }}"
    EVENTS_PER_SECOND={{ $config.parking.eventsPerSecond }}
    PARKING_PLATE_PATTERN="{{ $config.vehicle.platePattern }}"
    PARKING_PLATE_RANDOM_PROBABILITY={{ $config.vehicle.plateRandomProbability }}
    VEHICLE_COLORS="{{ $config.vehicle.colors }}"
    VEHICLE_TYPES="{{ $config.vehicle.types }}"
    MIN_PARKING_DURATION={{ $config.parking.minDuration }}
    MAX_PARKING_DURATION={{ $config.parking.maxDuration }}
    RESILIENCE_MAX_RETRIES={{ $root.Values.resilience.maxRetries }}
    RESILIENCE_BACKOFF_MS={{ $root.Values.resilience.backoffMs }}
    KAFKA_TOPIC="{{ $root.Values.kafka.topic }}"
    KAFKA_BOOTSTRAP_SERVERS="{{ $root.Values.kafka.bootstrapServers }}"
    PROMETHEUS_ENDPOINT="{{ $root.Values.monitoring.prometheusEndpoint }}"
---
{{- end }}
