apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: srvc-io
  namespace: apps
  labels:
    app: srvc-io
    type: backends
spec:
  serviceName: srvc-io
  replicas: "{{ .Values.replicas }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: srvc-io
  template:
    metadata:
      labels:
        app: srvc-io
        monitoring: "enabled"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: srvc-io
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: entrypoint
              mountPath: /mnt
            - name: config
              mountPath: /config
      volumes:
        - name: entrypoint
          configMap:
            name: srvc-io-entrypoint
            defaultMode: 0755
        - name: config
          projected:
            sources:
            {{- range .Values.configs }}
              - configMap:
                  name: srvc-io-{{ .id }}-config
                  items:
                    - key: config.env
                      path: srvc-io-{{ .id }}.env
            {{- end }}
