---
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.5/manifests/install.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=
  - ingress.yml
