---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.5/manifests/install.yaml
  - ingress.yml
  - argocd-apps

patches:
  - path: patch-argocd-ssh-cm.yml
