---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yml
  - pull-secrets.yml
# - srvc-io deployed by argocd as chart helm
  - repo-account
  - srvc-alert
  - srvc-notifier
  - secrets.yml
  - pod-monitor.yml

configMapGenerator:
  - name: apps-config
    namespace: apps
    literals:
      # GENERIC
      - LOG_LEVEL=INFO
      # REDIS
      - REDIS_HOSTS=rfs-kv.redis.svc.cluster.local:26379
      - REDIS_MASTER_NAME=mymaster
      - REDIS_USER_KEY_PREFIX="user:"
      # MINIO
      - S3_ENDPOINT=http://minio-svc.minio.svc.cluster.local:9000
      - S3_BUCKET=default
      # KAFKA
      - KAFKA_BOOTSTRAP_SERVERS=kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      - KAFKA_PARKING_TOPIC=parking-event-topic
      - KAFKA_ALERT_TOPIC=alert-event-topic
      - KAFKA_ENABLE_AUTO_COMMIT=false
      - KAFKA_AUTO_OFFSET_RESET=earliest
      # PROMETHEUS
      - PROMETHEUS_PORT=9090
      - PROMETHEUS_HOST=0.0.0.0
      # APP
      - APP_PORT=8080
      - APP_HOST=0.0.0.0
