---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yml
  - pull-secrets.yml
  - repo-account
  - srvc-alert
  - srvc-io
  - srvc-notifier
  - secrets.yml

configMapGenerator:
  - name: apps-config
    namespace: apps
    literals:
      # GENERIC
      - LOG_LEVEL=INFO
      # REDIS
      - REDIS_HOST=redis-0.redis.redis.svc.cluster.local
      - REDIS_PORT=6379
      # MINIO
      - S3_ENDPOINT=http://minio-0.minio.minio.svc.cluster.local:9000
      - S3_BUCKET=default
