---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: apps-monitor
  namespace: apps
  labels:
    app: apps
    type: metrics
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      monitoring: "enabled"
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    any: true
