---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: apps
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "azhzLXB1bGwtaW1hZ2U6UHpWZG41ejZQV3RvR2ZHRzNZdTY="
          }
      }
    }
type: kubernetes.io/dockerconfigjson
# echo -n "k8s-pull-image:PzVdn5z6PWtoGfGG3Yu6" | base64
