---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: apps
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "y7Dyyygvcix3e57czkAp"
          }
      }
    }
type: kubernetes.io/dockerconfigjson
# TODO: modify this
