---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: apps
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "azhzLXB1bGwtaW1hZ2U6eTdEeXl5Z3ZjaXgzZTU3Y3prQXA="
          }
      }
    }
type: kubernetes.io/dockerconfigjson
# echo -n "k8s-pull-image:y7Dyyygvcix3e57czkAp" | base64
