apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: apps
type: Opaque
stringData:
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: apps
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "changeThisToAStrongPassword"
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: "minio123"
