apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvc-alert
  namespace: apps
  labels:
    app: srvc-alert
    type: backends
spec:
  # replicas: 1 # Managed by HPA
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: srvc-alert
  template:
    metadata:
      labels:
        app: srvc-alert
        monitoring: "enabled"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090" 
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: srvc-alert
          image: registry.cri.epita.fr/mateo.lelong/inde1/srvc-alert:v0.1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: apps-config
            - secretRef:
                name: redis-secrets
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
